
	export default [
		{ 	
			id:'fwpfjirjf4t5',
			text:'This is question 1',
			type : 'select',
			answerOptions : ['red', 'blue', 'green'],
			correctAnswer : 'green',
			displayOptions : 0,
			answerAttempts : 0,
			inPlay : false,
			isAnswered:false,
            answerPlayer:0,
            difficulty : 'Easy',
            tags : [ 'Star Wars'],
            tictactoe:true,
            moneyquiz:true,
			private:false,
			showEdit:false,
        },
		{ 	
			id:'jbgeweoirw',
			text:'This is question 2',
			type : 'enter',
			answerOptions : [],
			correctAnswer : 'green',
			displayOptions : 0,
			answerAttempts : 0,
			inPlay : false,
			isAnswered:false,
            answerPlayer:1,
            difficulty : 'Easy',
            tags : ['Dr Who'],
            tictactoe:true,
            moneyquiz:true,
            private:false,
			showEdit:true,
		},
		{ 	
			id:'efwfwofnwnf',
			text:'This is question 3',
			type : 'select',
			answerOptions : ['red', 'blue', 'green'],
			correctAnswer : 'green',
			displayOptions : 0,
			answerAttempts : 0,
			inPlay : false,
			isAnswered:false,
			answerPlayer:0,
            difficulty : 'Medium',
            tags : ['LOTR'],
            tictactoe:true,
            moneyquiz:true,
            private:false,
		},
		{ 	
			id:'gwpfjirjf4t5',
			text:'This is question 4',
			type : 'select',
			answerOptions : ['red', 'blue', 'green'],
			correctAnswer : 'green',
			displayOptions : 0,
			answerAttempts : 0,
			inPlay : false,
			isAnswered:false,
			answerPlayer:0,
            difficulty : 'Medium',
            tags : ['Bible'],
            tictactoe:true,
            moneyquiz:true,
            private:false,
		},
		{ 	
			id:'gbgeweoirw',
			text:'This is question 5',
			type : 'enter',
			answerOptions : [],
			correctAnswer : 'green',
			displayOptions : 0,
			answerAttempts : 0,
			inPlay : false,
			isAnswered:false,
			answerPlayer:1,
            difficulty : 'Difficult',
            tags : ['Star Trek'],
            tictactoe:true,
            moneyquiz:true,
            private:false,
		},
		{ 	
			id:'gfwfwofnwnf',
			text:'This is question 6',
			type : 'select',
			answerOptions : ['red', 'blue', 'green'],
			correctAnswer : 'green',
			displayOptions : 0,
			answerAttempts : 0,
			inPlay : false,
			isAnswered:false,
			answerPlayer:0,
            difficulty : 'Trivia Master',
            tags : ['Star Trek'],
            tictactoe:true,
            moneyquiz:true,
            private:false,
		},
		{ 	
			id:'hwpfjirjf4t5',
			text:'This is question 7',
			type : 'select',
			answerOptions : ['red', 'blue', 'green'],
			correctAnswer : 'green',
			displayOptions : 0,
			answerAttempts : 0,
			inPlay : false,
			isAnswered:false,
			answerPlayer:0,
            difficulty : 'Easy',
            tags : ['History'],
            tictactoe:true,
            moneyquiz:true,
            private:false,
		},
		{ 	
			id:'hbgeweoirw',
			text:'This is question 8',
			type : 'enter',
			answerOptions : ['green', 'Green'],
			correctAnswer : 'green',
			displayOptions : 0,
			answerAttempts : 0,
			inPlay : false,
			isAnswered:false,
			answerPlayer:1,
            difficulty : 'Difficult',
            tags : ['Movies'],
            tictactoe:true,
            moneyquiz:true,
            private:false,
		},
		{ 	
			id:'hfwfwofnwnf',
			text:'This is question 9',
			type : 'select',
			answerOptions : ['red', 'blue', 'green'],
			correctAnswer : 'green',
			displayOptions : 0,
			answerAttempts : 0,
			inPlay : false,
			isAnswered:false,
			answerPlayer:0,
            difficulty : 'Medium',
            tags : ['Science'],
            tictactoe:true,
            moneyquiz:true,
            private:false,
		}
	]
